export default function Body4(props) {
    return (
    <>
    <section className="h-full max-w-md md:max-w-6xl mx-auto bg-white text-black">
    <div className="md:mx-20 mx-10">
         <div>
            <h5 className="md:text-xl mb-2 font-bold md:font-semibold mt-16 md:mt-52 text-sm">Pesan Tiket Kereta Api lebih Praktis Bebas Antri!</h5>
            <p className="text-xs md:text-sm text-[#58627a] text-justify">Berlibur ialah suatu kebutuhan yang sangat penting bagi kehidupan manusia. Hanya dengan cari tiket kereta api, cek tanggal dan jadwal kereta api sesuai dengan keinginan, dan reservasi tiket kereta Anda sudah dalam genggaman. Dulu, Anda harus membeli tiket KAI di stasiun langsung dan harus melewati antrian panjang, bukan? Namun kini Anda tidak perlu repot lagi untuk melihat jadwal serta melakukan pemesanan tiket kereta, karena Anda dapat dilakukan secara online hanya di Ticketing. Cek tiket KAI sekarang juga dan Anda juga tidak perlu takut kehabisan tiket kereta api karena bisa pesan tiket dari jauh-jauh hari. Hanya dengan tinggal pesan tiket kereta di Ticketing, simpan nomor kode booking tiket kai, cetak tiket kereta api di stasiun keberangkatan dan tiket kereta siap untuk keberangkatan dan kepulangan tempat tujuan. Lebih mudah dan praktis, bukan? Liburan jadi lebih menyenangkan karena Anda tidak perlu buang-buang waktu dan tenaga untuk antri membeli tiket kereta api. Metode pembayaran dapat Anda gunakan untuk beli tiket Kereta Api Indonesia (KAI) pun sangat lengkap dan terpercaya, mulai dari Qris, Dana, Indomaret, hingga pembayaran dengan Alfamart. Kalau bisa beli tiket kereta api online, kenapa harus capek-capek antri di stasiun? Anda juga dapat menikmati berbagai promo tiket kereta api yang menarik dari Ticketing. Jadi tunggu apa lagi? Ayo cek tiket kereta api online di Ticketing, dan dapatkan pengalaman mudah dan praktisnya pesan tiket KAI di Ticketing!</p>
        </div>
        <div className="mt-10">
            <h5 className="text-sm md:text-xl mb-2 font-bold md:font-semibold">Rasakan Manfaat Pilih Jadwal Tiket KAI Sesuai dengan Keinginan</h5>
            <p className="text-xs md:text-sm text-[#58627a] text-justify">Bepergian bersama keluarga dan sahabat merupakan saat-saat yang menyenangkan. Salah satu momen yang bisa membangun mood bepergian adalah saat-saat selama perjalanan ke tempat tujuan. Jangan sampai momen ini rusak dan mengganggu semangat jalan-jalan Anda akibat duduk berjauhan atau terpisah dari keluarga dan sahabat. Tidak hanya perasaan kurang nyaman dan aman karena duduk berdekatan dengan orang yang tidak dikenal,posisi duduk yang berjauhan ini juga bisa menyebabkan sulitnya berkomunikasi dengan teman perjalanan. Saat ini, tiket Kereta Api Indonesia (KAI) sudah semakin mudah diperoleh. Namun, penumpang tetap harus berhati-hati pada saat pembelian tiket kereta. Dengan membeli tiket kereta api online di Ticketing, Anda bisa terhindar dari penipuan, Mengapa? karena Ticketing merupakan situs remdi KAI. Anda bisa pilih sendiri tempat duduk yang diinginkan dan bebas dari risiko terpisah dari orang terdekat. Pembelian tiket kereta online ini didukung oleh berbagai pembayaran instan dengan pilihan rute perjalanan dan kelas yang lengkap. Anda juga bisa pilih tiket kereta api secara online di Ticketing berdasarkan harga dari yang termurah, baik untuk perjalanan solo Anda ataupun dengan orang-orang tersayang. Beli tiket kereta api online di nama website, rasakan kemudahan dan kenyamanannya!</p>
        </div>
        <div className="mt-10">
            <h5 className="text-sm md:text-xl mb-2 font-bold md:font-semibold">Cek Jadwal Kereta Api dan Dapatkan Harga Tiket Promo Termurah</h5>
            <p className="text-xs md:text-sm text-[#58627a] text-justify">Sebagai salah satu alat transportasi massal andalan masyarakat Indonesia, kini transportasi kereta api Indonesia sudah lebih memperbaiki service untuk para penumpang kereta yang nyaman dan aman. Maka, umumnya sarana transportasi jenis ini digunakan untuk mempermudah liburan, bisnis trip serta pulang kampung. Hal ini pula membuat jumlah penggunanya di Indonesia kian bertambah. Kini dengan cukup periksa dari mdartphone Anda untuk mendapatkan jadwal kereta, lengkap dengan harga termurah. Pesanlah tiket KAI setidaknya satu minggu sebelum keberangkatan. Selain untuk menghindari kehabisan tiket, memesan dari jauh hari juga akan memberikan Anda keleluasaan dalam memilih jadwal kereta api yang sesuai, karena stok masih tersedia banyak dan pilihan kelas serta kursi juga masih beragam. Hal ini tentu juga akan memungkinkan Anda untuk mengubah jadwal kereta api tanpa tergesa-gesa jika sewaktu-waktu Anda harus mengubahnya karena kebutuhan yang mendesak. Adapun tiket Kereta Api Indonesia sudah dapat dipesan sejak 90 hari sebelum tanggal keberangkatan. Mudah bukan? Tunggu apalagi? Beli tiket kereta api dengan harga terbaik hanya di Ticketing.</p>
        </div>
        <div className="mt-10">
            <h5 className="text-sm md:text-xl mb-2 font-bold md:font-semibold">Partner Remdi PT KAI Indonesia</h5>
            <p className="text-xs md:text-sm text-[#58627a] mb-20 text-justify">Sebagai perusahaan utama penyedia layanan kereta api di Indonesia, PT Kereta Api Indonesia (KAI) mengemban tugas yang sangat penting menyoal dunia perkeretaapian di Indonesia, diantaranya: menyediakan kemudahan transaksi tiket kereta api. Untuk itu, saat ini Ticketing telah menjadi partner remdi PT KAI. Ticketing menjalin kerjasama dengan KAI dalam hal penyediaan layanan pemesanan tiket kereta api online. Lewat Ticketing, pelanggan setia PT KAI Indonesia bisa menikmati segala kemudahan dan kenyamanan dalam transaksi tiket kereta api secara online. Cukup dengan mengakses laman tiket di Ticketing, anda bisa cari tiket kereta api dengan harga terbaik. Sebagai partner remdi PT KAI, tentu saja harga tiket kereta api yang ditampilkan sama persis dengan apa yang ditawarkan langsung oleh KAI. Selain itu, anda juga bisa memanfaatkan berbagai promo cashback dan penawaran menarik lainnya. Sebagai partner remdi PT KAI, keamanan dalam bertransaksi tiket kereta api di Ticketing tentunya sangat terjamin. Seluruh proses pemesanan tiket kereta api di Ticketing terjadi di bawah jalinan kerjasama remdi dengan PT KAI. Hal ini tentunya sudah termasuk proses persiapan dan evaluasi bersama yang sangat mendetail atas sistem pemesanan tersebut, guna memastikan segala prosedur berjalan dengan lancar. Jadi, tak perlu lagi khawatir membeli tiket secara online. Langsung beli tiket kereta online cepat dan tanpa repot hanya di Ticketing!</p>
        </div>
    </div>
</section>

<div className="max-w-md md:max-w-6xl mx-auto">
    <div className="border-b-2 bg-white text-black mx-5 md:mx-20"></div>
</div>
</>
    )
}